### ISSUE TITLE
Request: Playbook yaml for "How Ansible brought peace to my home"

### ISSUE THREAD

**Issue by ianhundere** [waverunner/articles#1]
Hey James,

I wanted to see if I could get a copy of the yaml files you used to configure your daughter's laptops. I'm doing a similar project and you had a nice list of software to start with.

Cheers / Thanks!

Ian

**Comment by waverunner** [comment]
Wow Ian ... sorry, I must have somehow missed this at the time it was posted. I haven't really looked here in ages, but then got this mysterious alert from github thus evening.
Sorry if I never responded!
